version: "3"
services:
  postgres12:
    image: postgres:12.2
    restart: "no"
    environment:
      - POSTGRES_USER=aldi
      - POSTGRES_PASSWORD=aldi
    volumes:
      - ./data:/data
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: "no"
    ports:
      - 6379:6379
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
      - "1025:25"
